# Generated by Django 3.2.5 on 2023-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_api', '0002_auto_20230615_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
